//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeShopApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class User
    {
        [RegularExpression("^[A-Za-z.'-]{1,}$", ErrorMessage = "Invalid First Name.")]
        [Required(ErrorMessage = "First Name is Required!")]
        public string FirstName { get; set; }

        [RegularExpression("^[A-Za-z.'-]{1,}$", ErrorMessage = "Invalid Last Name.")]
        [Required(ErrorMessage = "Last Name is Required!")]
        public string LastName { get; set; }

        [DataType(DataType.EmailAddress, ErrorMessage = "Invalid email format.")]
        [Required(ErrorMessage = "Email is Required!")]
        public string Email { get; set; }

        [RegularExpression("^[0-9]{3}-[0-9]{3}-[0-9]{4}", ErrorMessage = "Invalid Phone Number.")]
        [Required(ErrorMessage = "Phone Number is Required!")]
        public string PhoneNumber { get; set; }

        [RegularExpression("^(?=.*[0-9])(?=.*[a-zA-Z])[\\S]{8,20}$", ErrorMessage = "Invalid Password.")]
        [Required(ErrorMessage = "Password is Required!")]
        public string Password { get; set; }
    }
}
